### create
POST localhost:8081/article
Content-Type: application/json
Authorization: Bearer

{
  "title": "Ob-havo",
  "description": "ob-havo haqida malumot",
  "content": "123456",
  "image_id": "image_id",
  "region_id": 1,
  "category_id": 1,
  "articleTypesList": [1,2],
  "imageId": "",
  "regionId": 3,
  "categoryId": 1
}

### update article
GET localhost:8081/article/get5
