### create
POST localhost:8081/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6Iis5OTg5OTA0MzA2NDAiLCJpYXQiOjE3MzAzNzEyNzAsImV4cCI6MTczMDQ1NzY3MH0.F3r6x_1NLeDlsuLyZMfEEa4l36JlimB7BF7-iUqQPXQ

{
  "name": "Alijon",
  "surname": "Aliyev",
  "email": "alialiyev@gmail.com",
  "password": "alialiyev"
}

### update (admin)
PUT localhost:8081/profile/alialiyev@gmail.com
Content-Type: application/json

### update value (user)
PUT localhost:8081/profile/update/alialiyev@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6Iis5OTg5OTA0MzA2NDAiLCJpYXQiOjE3MzAzNzA4MTAsImV4cCI6MTczMDQ1NzIxMH0.6P_0A47uD7b3SKTt97A1KAgWJXQ_aop7pKRlWxMWJXg

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "valivaliyev@gmail.com",
  "password": "valivaliyev"
}

### getAll
GET localhost:8081/profile/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoiKzk5ODk5MDQzMDY0MCIsImlhdCI6MTczMDIwMDY4NywiZXhwIjoxNzMwMjg3MDg3fQ.KlZ7w7NO9_AaO1z6KPtamO06E4U0HdD8gL3nmXeK4nc









